### ISSUE TITLE
Symbolic evaluation of `CUGate` raises an unexpected `TypeError`

### ISSUE THREAD

**Issue by adrianor** [SimoneGasperini/qiskit-symb#4]
There is an issue when one tries to use the package and the circuit contains controlled unitaries. For instance the circuit
```python
from qiskit.circuit import QuantumRegister, ClassicalRegister, QuantumCircuit, Parameter
import numpy as np

st0 = Parameter("st0")
st1 = Parameter("st1")

def u1red_cr_overrot(alpha, theta):
    qreg_q = QuantumRegister(2, "q")
    creg_c = ClassicalRegister(2, "c")
    circuit = QuantumCircuit(qreg_q, creg_c)
    circuit.u(1.570796326794897, -2.9755113931440857, 4.71238898038469 + st1, qreg_q[1])
    circuit.u(1.8942714348583476, -4.71238898038469, 0.0 + st0, qreg_q[0])
    circuit.cu(np.pi / 2, np.pi / 2, -np.pi / 2, 0, qreg_q[1], qreg_q[0])
    return qreg_q, creg_c, circuit
```
raises no problem when one draws it:
```python
phin = 0.0
theta = np.pi / 8.0

qreg_q, creg_c, circuit = u1red_cr_overrot(phin, theta)
circuit.draw("mpl")
```
But if one tries to get its `Statevector` form
```python
from qiskit_symb.quantum_info import Statevector

statevec = Statevector(circuit)
```
it raises the following error message:
```
TypeError: CUGate.__init__() got multiple values for argument 'ctrl_qubits'
```
Note that this also happens if one wants to obtain its `Operator` form:
```python
from qiskit_symb.quantum_info import Operator

op = Operator(circuit)
```

**Comment by SimoneGasperini** [comment]
Thank you @adrianor for reporting this.
The problem here arises from a minor difference in the signature of the controlled unitary gate in Qiskit and in `qiskit-symb`. In Qiskit, the [`CUGate`](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CUGate.html) constructor (and the corresponding [`QuantumCircuit.cu`](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html#qiskit.circuit.QuantumCircuit.cu) method you are using in your code) takes 3 angles _theta_, _phi_, _lam_ + one extra _gamma_ for the global phase while, in `qiskit-symb`, the last parameter _gamma_ is omitted.
From my point of view, this is actually a small but relevant inconsistency in Qiskit, since `CUGate` is the only gate that takes one more "angle parameter" compared to its corresponding [`UGate`](https://qiskit.org/documentation/stubs/qiskit.circuit.library.UGate.html) (not controlled) and indeed several open issues on the main `qiskit-terra` repository are related to this problem (e.g. [#9763](https://github.com/Qiskit/qiskit-terra/issues/9763), [#7326](https://github.com/Qiskit/qiskit-terra/issues/7326)).

This is not handled correctly in `qiskit-symb` and the error message is very misleading. So, waiting for the problem to be resolved in Qiskit itself, I can implement a quick fix in `qiskit-symb` as a "temporary workaround".

**Comment by SimoneGasperini** [comment]
Thank you @adrianor for reporting this.
The problem here arises from a minor difference in the signature of the controlled unitary gate in Qiskit and in `qiskit-symb`. In Qiskit, the [`CUGate`](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CUGate.html) constructor (and the corresponding [`QuantumCircuit.cu`](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html#qiskit.circuit.QuantumCircuit.cu) method you are using in your code) takes 3 angles _theta_, _phi_, _lam_ + the global phase _gamma_ while, in `qiskit-symb`, the last parameter _gamma_ is omitted.
From my point of view, this is actually a small but relevant inconsistency in Qiskit, since `CUGate` is the only gate that takes one extra "angle parameter" compared to its corresponding [`UGate`](https://qiskit.org/documentation/stubs/qiskit.circuit.library.UGate.html) (not controlled) and indeed several open issues on the main `qiskit-terra` repository are related to this problem (e.g. [#9763](https://github.com/Qiskit/qiskit-terra/issues/9763), [#7326](https://github.com/Qiskit/qiskit-terra/issues/7326)).

This is not handled correctly in `qiskit-symb` and the error message is very misleading. So, waiting for the problem to be resolved in Qiskit itself, I can implement a quick fix in `qiskit-symb` as a "temporary workaround".

**Comment by SimoneGasperini** [comment]
Thank you @adrianor for reporting this.
The problem here arises from a minor difference in the signature of the controlled unitary gate in Qiskit and in qiskit-symb. In Qiskit, the [CUGate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CUGate.html) constructor (and the corresponding [QuantumCircuit.cu](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html#qiskit.circuit.QuantumCircuit.cu) method you are using in your code) takes 3 angles theta, phi, lam + the global phase gamma while, in qiskit-symb, the last parameter gamma is omitted.
From my point of view, this is actually a small but relevant inconsistency in Qiskit, since CUGate is the only gate that takes one extra "angle parameter" compared to its corresponding [UGate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.UGate.html) (not controlled) and indeed several open issues on the main qiskit-terra repository are related to this problem (e.g. https://github.com/Qiskit/qiskit-terra/issues/9763, https://github.com/Qiskit/qiskit-terra/issues/7326).

However, this is for sure not handled correctly in `qiskit-symb` and the error message is very misleading. So, waiting for the problem to be resolved in Qiskit itself, I can implement an hot-fix in `qiskit-symb` as a "temporary workaround".

**Comment by SimoneGasperini** [comment]
Thank you @adrianor for reporting this.
The problem here arises from a minor difference in the signature of the controlled unitary gate in Qiskit and in `qiskit-symb`. In Qiskit, the [`CUGate`](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CUGate.html) constructor (and the corresponding [`QuantumCircuit.cu`](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html#qiskit.circuit.QuantumCircuit.cu) method you are using in your code) takes 3 angles _theta_, _phi_, _lam_ + the global phase _gamma_ while, in `qiskit-symb`, the last parameter _gamma_ is omitted.
From my point of view, this is actually a small but relevant inconsistency in Qiskit, since `CUGate` is the only gate that takes one extra "angle parameter" compared to its corresponding [`UGate`](https://qiskit.org/documentation/stubs/qiskit.circuit.library.UGate.html) (not controlled) and indeed several open issues on the main `qiskit-terra` repository are related to this problem (e.g. https://github.com/Qiskit/qiskit-terra/issues/9763, https://github.com/Qiskit/qiskit-terra/issues/7326).

However, this is for sure not handled correctly in `qiskit-symb` and the error message is very misleading. So, waiting for the problem to be properly solved in Qiskit itself, I can temporarily fix `qiskit-symb` so that it shows an appropriate error message by marking the `CUGate` as "not implemented".

**Comment by SimoneGasperini** [comment]
Meanwhile, you can use the Qiskit transpiler to work around the problem and run your code with no errors:
```python
import numpy as np
from qiskit import transpile
from qiskit.circuit import QuantumRegister, ClassicalRegister, QuantumCircuit, Parameter
from qiskit_symb.utils import get_symbolic_gates_names

st0 = Parameter("st0")
st1 = Parameter("st1")

def u1red_cr_overrot(alpha, theta):
    qreg_q = QuantumRegister(2, "q")
    creg_c = ClassicalRegister(2, "c")
    circuit = QuantumCircuit(qreg_q, creg_c)
    circuit.u(1.570796326794897, -2.9755113931440857, 4.71238898038469 + st1, qreg_q[1])
    circuit.u(1.8942714348583476, -4.71238898038469, 0.0 + st0, qreg_q[0])
    circuit.cu(np.pi / 2, np.pi / 2, -np.pi / 2, 0, qreg_q[1], qreg_q[0])
    symbolic_gates = get_symbolic_gates_names()
    symbolic_gates.remove("cu")
    circuit = transpile(circuit, basis_gates=symbolic_gates)
    return qreg_q, creg_c, circuit
```

In this case, the `CUGate` transforms into a `CU3Gate` but the final circuit is always exactly equivalent to the original. Note that this also works correctly when the global phase parameter _gamma_ is not 0.

**Comment by adrianor** [comment]
Ok so with the changes that you propose the "numerical evaluation" of circuits remains the same. But still there is some problem with the feature. If run the circuit above, all works fine. Now, I have to say that the above circuit is just an extract of a bigger circuit that I am using, its fullest form is

```
from qiskit.circuit import Parameter
from qiskit_symb.quantum_info import Operator
from qiskit_symb.quantum_info import Statevector

st0 = Parameter('st0')
st1 = Parameter('st1')

def u1red_cr_overrot(alpha,theta,phi1):
    qreg_q = QuantumRegister(2, 'q')
    creg_c = ClassicalRegister(2, 'c')
    circuit = QuantumCircuit(qreg_q, creg_c)
    # State preparation
    circuit.ry(theta, qreg_q[0])
    circuit.p(alpha, qreg_q[0])
    circuit.ry(theta, qreg_q[1])
    circuit.p(alpha, qreg_q[1])
    #
    circuit.p(-2.838767630222221, qreg_q[1])
    circuit.p(-8.881784197001252e-16, qreg_q[0])
    circuit.x(qreg_q[1])
    circuit.x(qreg_q[0])
    circuit.p(-2.838767630222221, qreg_q[1])
    circuit.p(-8.881784197001252e-16, qreg_q[0])
    circuit.x(qreg_q[1])
    circuit.x(qreg_q[0])
    circuit.u(1.570796326794897,-2.9755113931440857,4.71238898038469+st1, qreg_q[1])
    circuit.u(1.8942714348583476,-4.71238898038469,0.0+st0, qreg_q[0])
    ##circuit.cx(qreg_q[1], qreg_q[0])
    # Decomposition of (IX)^-1/2
    circuit.sxdg(qreg_q[0])
    # Decomposition U=exp(-i*pi*sigmaz \otimes sigmax/4)
    circuit.cu(np.pi/2, np.pi/2, -np.pi/2, 0, qreg_q[1], qreg_q[0])
    circuit.x(qreg_q[1])
    circuit.x(qreg_q[0])
    circuit.cu(-np.pi/2, np.pi/2, -np.pi/2, 0, qreg_q[1], qreg_q[0])
    circuit.x(qreg_q[1])
    circuit.x(qreg_q[0])
    # Over/Under-rotation
    circuit.cu(-phi1, np.pi/2, -np.pi/2, 0, qreg_q[1], qreg_q[0])
    circuit.x(qreg_q[1])
    circuit.x(qreg_q[0])
    circuit.cu(phi1, np.pi/2, -np.pi/2, 0, qreg_q[1], qreg_q[0])
    circuit.x(qreg_q[1])
    circuit.x(qreg_q[0])
    # Decomposition (ZI)^-1/2
    circuit.p(-np.pi/2, qreg_q[1])
    # Fix the global phase
    circuit.p(np.pi/4, qreg_q[0])
    circuit.x(qreg_q[0])
    circuit.p(np.pi/4, qreg_q[0])
    circuit.x(qreg_q[0])
    circuit.rx(1.734633290070176, qreg_q[1])
    circuit.rz(-0.8120139656904724+0.1, qreg_q[0])
    ##circuit.cx(qreg_q[1], qreg_q[0])
    # Decomposition of (IX)^-1/2
    circuit.sxdg(qreg_q[0])
    # Decomposition U=exp(-i*pi*sigmaz \otimes sigmax/4)
    circuit.cu(np.pi/2, np.pi/2, -np.pi/2, 0, qreg_q[1], qreg_q[0])
    circuit.x(qreg_q[1])
    circuit.x(qreg_q[0])
    circuit.cu(-np.pi/2, np.pi/2, -np.pi/2, 0, qreg_q[1], qreg_q[0])
    circuit.x(qreg_q[1])
    circuit.x(qreg_q[0])
    # Over/Under-rotation
    circuit.cu(phi1, np.pi/2, -np.pi/2, 0, qreg_q[1], qreg_q[0])
    circuit.x(qreg_q[1])
    circuit.x(qreg_q[0])
    circuit.cu(-phi1, np.pi/2, -np.pi/2, 0, qreg_q[1], qreg_q[0])
    circuit.x(qreg_q[1])
    circuit.x(qreg_q[0])
    # Decomposition (ZI)^-1/2
    circuit.p(-np.pi/2, qreg_q[1])
    # Fix the global phase of ONE CNOT (!)
    circuit.p(np.pi/4, qreg_q[0])
    circuit.x(qreg_q[0])
    circuit.p(np.pi/4, qreg_q[0])
    circuit.x(qreg_q[0])
    circuit.u(1.5707963267948977,-1.5707963267948961,5.511453999998734, qreg_q[1])
    circuit.u(2.9148925083682986,8.881784197001252e-16,4.712388980384691, qreg_q[0])
    # This is to trick qiskit to accept gate cu (along with the header 
    # from qiskit_symb.utils import get_symbolic_gates_names)
    symbolic_gates = get_symbolic_gates_names()
    symbolic_gates.remove("cu")
    circuit = transpile(circuit, basis_gates=symbolic_gates)
    return qreg_q, creg_c, circuit
```
In this case, there seems to be a bottleneck:

```
op = Operator(circuit) # works fine
op.to_sympy() # bottleneck here

circuit = circuit.decompose() # works fine
statevec = Statevector(circuit).to_lambda() # bottleneck here
```
I haven't done it, but it might be I can continue my works without the bottlenecks mentioned above. Yet, it might be useful for the health of the package address the above issues.

**Comment by adrianor** [comment]
In fact, `to_xx` doesn't work for either of the option, lambda, numpy or scipy.

**Comment by SimoneGasperini** [comment]
Hello @adrianor! First of all, this problem is completely unrelated to the `CUGate` issue we were discussing here, so I would recommend to open a new issue for this.

Anyway, the reason why both methods `to_sympy` and `to_numpy` run indefinitely is that your circuit is unfortunately already too deep to have a nice symbolic representation of the corresponding statevector or operator. Indeed, these methods are not actually computing anything (the symbolic evaluation takes place at the line `sv = Statevector(circuit)` or `op = Operator(circuit)`) but they simply return a formatted result to be possibly displayed: this turns out to be not possible in your case because the final symbolic expression is too long and complex.

The method `to_lambda`, instead, transforms the symbolic object in a Python lambda function.
```python
from qiskit_symb.quantum_info import Statevector

func = Statevector(circuit).to_lambda()
```
On my PC, the code above takes few minutes to run with your full circuit but it finally returns the expected output function. Then, you can call it very efficiently as many times as you want, passing different parameters values at each call.
Unfortunately, the conversion is very slow because this feature has not been optimized yet: in particular, the required time scales exponentially with the circuit depth (see [this blog](https://medium.com/qiskit/qiskit-symb-a-qiskit-ecosystem-package-for-symbolic-quantum-computation-b6b4407fa705)). However, a major update will be hopefully available soon as part of the next release of the package and it should make the required time linear with the circuit depth.

**Comment by adrianor** [comment]
Thanks for running my circuit in your local pc. Unfortunately for my computer it is impossible to even cast the lambda function properly; the kernel just keep running indefinitely.

Anyway, it seems I will need to see how to do this manually. Hopefully, future releases will automate this.
